### ISSUE TITLE
Next minor release (2.5.0)

### ISSUE THREAD

**Issue by RST-J** [ruby-json-schema/json-schema#202]
I think we should release a new version of `json-schema` soon. I'll add a list of tasks to be done before we release:
- [x] merge JSON::Schema::Loader #175 
- [x] merge fix for $ref issue #200
- [x] merge fix for multi-json issue and about ignored tests #196 
- [x] bump version number

What else? I also think, #182 and #183 are candidates for 2.5.0 or is that still too much in progress?
