### ISSUE TITLE
Consider releasing 2.5.1

### ISSUE THREAD

**Issue by inglesp** [ruby-json-schema/json-schema#227]
I'd love to be able to make use of #216, but can't until a new version of the gem is released.  (I've got another gem that depends on this gem, and you can't put a link to github in a gemspec...)

Is there anything I can do to help get this released?

**Comment by RST-J** [comment]
Generally it would be no problem to release a new version, I think.
But if we do that I would like to get some more open things in:
- [] #226 updated addressable dependency
- [] #224 ensured update for common test suite
- [] #223 adding Ruby 2.2. to the Travis build
- [] #221 renamed variable
- [] #206 remove support for alternate JSON backends

They are all ready and need only one more approval and in case of #206 a minor adjustment.

**Comment by RST-J** [comment]
I prepared a milestone and a (visible) task list in #228.
