### ISSUE TITLE
Prepare release of 2.5.1

### ISSUE THREAD

**Issue by RST-J** [ruby-json-schema/json-schema#228]
I've prepared a milestone for the next minor release [2.5.1](https://github.com/ruby-json-schema/json-schema/milestones/v2.5.1) as requested in #227.

If think these should be added before we release:
- [x] #230 fixed error message for strict validation
- [x] #226 updated addressable dependency
- [x] #224 ensured update for common test suite
- [x] #223 adding Ruby 2.2. to the Travis build
- [x] #221 renamed variable
- [x] #219 issue with integer and fload equality

Anything more?

**Comment by iainbeeston** [comment]
Isn't #206 too large a change for a patch release? (I believe it was slated
for version 3?) I don't have a problem with the idea of releasing that as
2.6 though

**Comment by RST-J** [comment]
I can't see a clear tendency in the discussion of #206. But I agree, if we decide to take this in for the next release, we should have a minor release.
What do you think @pd @hoxworth?

**Comment by hoxworth** [comment]
I'd personally prefer #206 to be a major release, considering it will break
backwards compatibility with users that presently use the JSON parsers that
are currently supported.

**Comment by RST-J** [comment]
That makes sense, agreed.

**Comment by iainbeeston** [comment]
If anyone can help review those and get them merged, that would be great (reminder to self - I need to review #219 !)

**Comment by iainbeeston** [comment]
Oh, and I suggest we also try to fix #220 for the release (no pull request yet...)

**Comment by RST-J** [comment]
@pd, @hoxworth got someone of you two time to do the remaining reviews so we can release in the near future?

**Comment by inglesp** [comment]
I've reviewed all of these, and I think they're all fine, with just one comment.  Is there anything else I can do to help get this ticket closed?

**Comment by iainbeeston** [comment]
@pd ? @hoxworth? Sorry to bother you but we really need some members of the core team to review before we can merge those changes and make the release

**Comment by hoxworth** [comment]
These all look good. Sorry I haven't been around, other things keeping my attention. I'll +1 these individually momentarily. 

For the future, never be afraid to push minor / patch releases when there is code ready. Even if we're waiting for +1's on other pull requests, as long as they don't block one another, it would be better to get fixes / better code available for general availability sooner rather than later in a big chunk.

**Comment by iainbeeston** [comment]
Great, thanks for taking a look @hoxworth. I'll remember that next time.

@RST-J Do you want to make the release or shall I?

**Comment by RST-J** [comment]
@iainbeeston go ahead, I'm busy today and could only release later in the evening or tomorrow.

**Comment by iainbeeston** [comment]
I've just made the release, get it while it's hot.

**Comment by inglesp** [comment]
Thanks everyone!
