### ISSUE TITLE
Changes needed before 3.0 release

### ISSUE THREAD

**Issue by iainbeeston** [ruby-json-schema/json-schema#247]
- [ ] [Changelog](https://github.com/ruby-json-schema/json-schema/issues/232)
- [ ] [Remove support for yajl and multijson](https://github.com/ruby-json-schema/json-schema/pull/206)
- [ ] [$ref autoloading is disabled by default](https://github.com/ruby-json-schema/json-schema/issues/152)
- [ ] [Replace UUID module with something faster](https://github.com/ruby-json-schema/json-schema/issues/151)
- [ ] Remove ruby 1.8 support
- [ ] [i18n support for error messages](https://github.com/ruby-json-schema/json-schema/issues/97)
- [ ] Stop stringifying input hashes
- [ ] Stop autodetecting/autoloading from input string urls (extract to an extension?)
- [ ] Stop inserting defaults (extract to an extension?)
- [ ] Remove list-mode (extract to an extension?)
- [ ] [Reduce the number of class variables in Validator](https://github.com/ruby-json-schema/json-schema/issues/242)
